[tasks.default]
clear = true
dependencies = [
  "fmt",
  "check",
  "clippy",
  "release",
  "install"
]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.release]
dependencies = ["build-release"]

[tasks.dev]
dependencies = ["build-dev"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.build-dev]
command = "cargo"
args = ["install", "--path", ".", "--debug"]

[tasks.build-release]
command = "cargo"
args = ["install", "--path", "."]

[tasks.install]
dependencies = ["astro-language-server-setup"]
script = """
export xdg_data_dir="$HOME/.local/share"
export plugin_dir="plugins/robin.lapce-astro"

mkdir -p ${xdg_data_dir}/lapce-stable/${plugin_dir}/bin
yes | cp -i bin/lapce-astro.wasm ${xdg_data_dir}/lapce-stable/${plugin_dir}/bin
yes | cp -i volt.toml ${xdg_data_dir}/lapce-stable/${plugin_dir}/
yes | cp -R language-server ${xdg_data_dir}/lapce-stable/${plugin_dir}/
"""

[tasks.astro-language-server-setup]
command = "pnpm"
args = ["install", "--prefix", "language-server"]
