name = "lapce-astro"
version = "0.0.1"
author = "robin"
display-name = "astro"
description = "Astro language support for Lapce"
wasm = "bin/lapce-astro.wasm"
repository = "https://github.com/robinv8/lapce-astro.git"
icon = "./logo.png"

[activation]
language = ['astro']
workspace-contains = []

[config."lsp.serverPath"]
default = ""
description = "Path to custom LSP executable"

